locales = [ "es-ES", "es-MX", "fr", "ja",]
[[paths]]
reference = "templates/pages/home/blog/new-blog-post.pot"
l10n = "locales/{locale}/pages/home/blog/new-blog-post.po"

[[paths]]
reference = "templates/pages/home/blog.pot"
l10n = "locales/{locale}/pages/home/blog.po"

